### PR TITLE
Use MRI Ruby

### PR DESCRIPTION
**Pull request by DaveBlooman**

### CODE REVIEW

**Comment by kenoir** [comment]
I can't let you do that Dave.

The code in this gem is intended for JVM threads. Be careful that there
aren't untested perf implications.

**Comment by DaveBlooman** [comment]
@kenoir I will rewrite it then.  What do you think the performance gains were from using JRuby over MRI?

**Comment by kenoir** [comment]
Avoiding the [GIL](https://en.wikipedia.org/wiki/Global_interpreter_lock).

Native Ruby does not do multi-threading well, meaning you lose some of the benefit of multi-core systems which is basically all of them. This gem is using a mutex which I wouldn't expect unless something is using it in a threaded fashion.

**Comment by DaveBlooman** [comment]
Did you ever do any benchmarks, maybe it is a time to see how fast 2.3 is Vs JRuby

**Comment by kenoir** [comment]
Meh, probably but I don't remember the outcome now (or have anything I can find).

http://www.isrubyfastyet.com/

Notice JRuby is fastest (by a tiny bit for rails requests) but has by far the bigger memory footprint and startup time. You might be better off switching to MRI if the performance in your case isn't compromised.

**Comment by Integralist** [comment]
I'd assume that without the mutex, even we the GIL, there would be concerns about operation access because there's still non-deterministic behaviour (e.g. concurrency; process switching still occurs with the GIL) so it's likely the mutex should stay even with MRI, I guess?

I don't think we have many concerns regarding performance per se, but it's definitely something that should be benchmarked. 

Dave's going to switch to latest JRuby as a precaution for now. But we'll look to move to MRI if things prove to be consistent

**Comment by kenoir** [comment]
> I'd assume that without the mutex, even we the GIL, there would be concerns about operation access because there's still non-deterministic behaviour (e.g. concurrency; process switching still occurs with the GIL) so it's likely the mutex should stay even with MRI, I guess?

I'd think so.

**Pull request closed without merging**
